### PR TITLE
allow statistical input

### PR DESCRIPTION
**Pull request by kilojoules**
Users may only have statistical information about a wind rose. Often these statistics are summarized by direction-specific frequencies and Weibull scale/shape factors or mean wind seeds. The `weibul_factors` and `mean_values` arguments allows users to input the statistics, expecting the `direction` and `var` arguments to describe speed statistics for each direction.

Example usage:

```python
    import urllib
    from windrose import WindroseAxes
    from matplotlib import pyplot as plt
    import numpy as np
    urllib.urlretrieve('https://raw.githubusercontent.com/WISDEM/FLORISSE/develop/test/input_files/windrose_amalia_directionally_averaged_speeds.txt', 'windrose_amalia_directionally_averaged_speeds.txt')
    fig = plt.figure(figsize=(12, 8), dpi=80, facecolor='w', edgecolor='w')
    ax = WindroseAxes(fig, [0.1, 0.1, 0.8, 0.8], axisbg='w')
    fig.add_axes(ax)
    windRose = np.loadtxt('windrose_amalia_directionally_averaged_speeds.txt')
    indexes = np.where(windRose[:, 1] > 0.1)
    windDirections = windRose[indexes[0], 0]
    windSpeeds = windRose[indexes[0], 1] * 2 / np.sqrt(np.pi) # convert from mean wind speed to weibull scale factor
    windFrequencies = windRose[indexes[0], 2]
    size  = len(windDirections)
    ax.box(windDirections, windSpeeds, frequency=windFrequencies, mean_values=1, bins=[15, 18, 20, 23, 25], nsector=72)
    #ax.box(windDirections, [[windSpeeds[i], 2] for i in range(len(windSpeeds))], frequency=windFrequencies, weibull_factors=1, bins=[15, 18, 20, 23, 25], nsector=72)
    ax.set_yticklabels([])
    plt.show()
```

### CODE REVIEW

**Comment by scls19fr** [comment]
Under Python 3 I'm getting `AttributeError: module 'urllib' has no attribute 'urlretrieve'`

Maybe you might use `requests` which support both Python 2 and Python 3 with a nice API.

```python
import requests
url = 'https://raw.githubusercontent.com/WISDEM/FLORISSE/develop/test/input_files/windrose_amalia_directionally_averaged_speeds.txt'
with open('windrose_amalia_directionally_averaged_speeds.txt', 'w') as fd:
    response = requests.get(url)
    fd.write(response.text)
...
windRose = np.loadtxt('windrose_amalia_directionally_averaged_speeds.txt')
```

or even without file creation using `StringIO`


```python
import requests
try:
    from io import StringIO  # Python 3
except ImportError:
    from StringIO import StringIO  # Python 2
url = 'https://raw.githubusercontent.com/WISDEM/FLORISSE/develop/test/input_files/windrose_amalia_dir
response = requests.get(url)
...
windRose = np.loadtxt(StringIO(response.text))
```

I triggered again Travis CI but it seems to be failing.

Maybe you should also put some doc for this new feature.
A sample data to use this feature could also be stored in this repository.

**Comment by kilojoules** [comment]
I added the example script and data. I tested the script with python2 and python3.5. It looks like it passes Travis CI now.

**Comment by scls19fr** [comment]
LGTM

Closes #48

Thanks again @kilojoules

**Comment by kilojoules** [comment]
Thanks for incorporating this feature @scls19fr 

I realized I left a typo in the example script—I don't want to convert to Weibull scale factors when using the `mean_valus` option. https://github.com/kilojoules/windrose/commit/55fb33017b8ce1033f16eaf25d44b9773ed5b7a3

**Comment by scls19fr** [comment]
with this "fix" it raises
```python
Traceback (most recent call last):
  File "example_statistical_input.py", line 13, in <module>
    ax.box(windDirections, windSpeeds, frequency=windFrequencies, mean_values=1, bins=[15, 18, 20, 23, 25], nsector=72)
NameError: name 'windSpeeds' is not defined
```

without it, it also raises an error

```python
$ python example_statistical_input.py
Traceback (most recent call last):
  File "example_statistical_input.py", line 13, in <module>
    ax.box(windDirections, windSpeeds, frequency=windFrequencies, mean_values=1, bins=[15, 18, 20, 23, 25], nsector=72)
  File "/Users/scls/anaconda/lib/python3.5/site-packages/windrose/windrose.py", line 444, in box
    zorder=zorder, **kwargs)
  File "/Users/scls/anaconda/lib/python3.5/site-packages/matplotlib/patches.py", line 638, in __init__
    Patch.__init__(self, **kwargs)
  File "/Users/scls/anaconda/lib/python3.5/site-packages/matplotlib/patches.py", line 123, in __init__
    self.update(kwargs)
  File "/Users/scls/anaconda/lib/python3.5/site-packages/matplotlib/artist.py", line 859, in update
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property mean_values
```

**Comment by kilojoules** [comment]
@scls19fr 

Thank you. I had commented out the line converting average wind speeds to weibull factors and forgot to add a line extracting the average wind speeds.  https://github.com/kilojoules/windrose/commit/c19462a988d818fa2e98acd0e9c469d54a8be9b5

The second error you posted surprised me. I do not get that error on my system. Are you sure you installed my PR? I pop that argument in line 230 of `windrose.py`.

**Comment by scls19fr** [comment]
Oh yes! you are right I didn't 

    $ pip uninstall windrose

before 

    $ sudo python setup.py install


It's ok now.
I've just use `dirname` in order to be able to run example both from sample directory or from an other directory.

https://github.com/scls19fr/windrose/commit/8db6c80e0d594dd1d7c463088157dd6d43ff3f93

**Pull request merged**
