### PR TITLE
added optional argument decimal_places

### PR DESCRIPTION
**Pull request by xmnlab**
#27 - added optional argument decimal_places in legend function to show legend bins with decimal places different of 1

### CODE REVIEW

**Comment by scls19fr** [comment]
Thanks a lot @xmnlab for your PR but I can't accept it until it's not respecting PEP8.

I'm using `flake8` with Travis CI so you just need to fix PEP8.

see https://travis-ci.org/scls19fr/windrose/jobs/109479397

You just need to remove some useless spaces.

```
windrose/windrose.py:181:1: W293 blank line contains whitespace
windrose/windrose.py:183:49: W291 trailing whitespace
windrose/windrose.py:186:1: W293 blank line contains whitespace
windrose/windrose.py:192:1: W293 blank line contains whitespace
windrose/windrose.py:199:1: W293 blank line contains whitespace
windrose/windrose.py:201:1: W293 blank line contains whitespace
```

You can try it before committing using:

```
flake8 --ignore=E501 windrose samples tests
```

Thanks again for your PR

**Comment by xmnlab** [comment]
Thank you @scls19fr about the feedback.
Sorry about this fault. I will see that asap !

I cannot do that right now, but I go to do that today yet.

My best,

**Comment by xmnlab** [comment]
@scls19fr do you know if something is wrong with 49da7a6 check?

**Comment by scls19fr** [comment]
I thought this kind of quoting was same, isn't it ?

**Comment by scls19fr** [comment]
Thanks for your contribution @xmnlab

**Comment by scls19fr** [comment]
Closes https://github.com/scls19fr/windrose/pull/28

**Comment by xmnlab** [comment]
thank you @scls19fr !

**Pull request merged**
