### PR TITLE
Fixed typo in legend labels

### PR DESCRIPTION
**Pull request by MarcoForte**

### CODE REVIEW

**Comment by scls19fr** [comment]
Sorry but that's not a typo

This kind of interval is called a half-open (exclusive) interval
https://en.wikipedia.org/wiki/Interval_(mathematics)

    [1.0;2.0[
    [2.0;3.0[

 means

    1.0 <= speed < 2.0
    2.0 <= speed < 3.0

Such interval

    [1.0;2.0]
    [2.0;3.0]

would mean

    1.0 <= speed <= 2.0
    2.0 <= speed <= 3.0

so 2.0 could belongs to 2 intervals...

You might also have a look at
https://www.quora.com/Why-are-Python-ranges-half-open-exclusive-instead-of-closed-inclusive

**Comment by MarcoForte** [comment]
Oh fair enough. I've seen alot of intervals in my time and never seen a
half open interval written that way. Its always been with a ")" for me. Out
of curiosity do you have examples of using "[" instead?
On Nov 29, 2015 6:51 PM, "scls19fr" <notifications@github.com> wrote:

Sorry but that's not a typo

This kind of interval is called a half-open (exclusive) interval
https://en.wikipedia.org/wiki/Interval_(mathematics)

[1.0;2.0[
[2.0;3.0[

means

1.0 <= speed < 2.0
2.0 <= speed < 3.0

Such interval

[1.0;2.0]
[2.0;3.0]

would mean

1.0 <= speed <= 2.0
2.0 <= speed <= 3.0

so 2.0 could belongs to 2 intervals...

You might also have a look at
https://www.quora.com/Why-are-Python-ranges-half-open-exclusive-instead-of-closed-inclusive

—
Reply to this email directly or view it on GitHub
<https://github.com/scls19fr/windrose/pull/16#issuecomment-160448151>.

**Comment by scls19fr** [comment]
I'm sorry... I'm french ;-)

https://fr.wikipedia.org/wiki/Intervalle_(math%C3%A9matiques)

**Comment by scls19fr** [comment]
I wasn't aware when I wrote this package that I will have to deal with i18n and l10n !!!

Feel free to commit on this...

The idea becoming that we should detect if we need french notations on a given system.

I haven't done this kind of stuff before.

**Comment by MarcoForte** [comment]
That certainly explains it, I'm going to change it for my personal project. I don't think it's worth complicating things to account for differences in notation. Thanks for windrose though, I like it as a whole.

**Comment by scls19fr** [comment]
Superseed by PR https://github.com/scls19fr/windrose/pull/23

**Pull request closed without merging**
